### ISSUE TITLE
Can the size of the image training be modified, such as 512 or 1024?

### ISSUE THREAD

**Issue by GZ-YourZY** [YuchuanTian/U-DiT#3]
This is a great work, but I wonder if the image training size can be changed to, say, 512 or 1024, which would allow for more realistic and detailed images.

**Comment by YuchuanTian** [comment]
Thank you! I really appreciate you like our work. Yeah, we have tried training size 512. We have updated the ArXiv manuscript to include the results, which will be released soon.
