### ISSUE TITLE
Questions about the global and local attention in U-DiT Block

### ISSUE THREAD

**Issue by yyk-wew** [YuchuanTian/U-DiT#4]
Thanks for sharing your great work! 
I am confused when reading the following lines from U-DiT block implementation.

https://github.com/YuchuanTian/U-DiT/blob/b810129f30e789fa781773d572c16e577d8498d3/udit_models.py#L512-L521

According to the comment, the two attention modules here are for local and global interaction each. But it seems that they are of the same initialization and both do local attention with downsampling?

Please let me know if i'm wrong somewhere.

**Comment by YuchuanTian** [comment]
I am sorry for that. Yes, you are right: both modules do local attention. The reason we leave these comments here is that we borrow some codes from our previous work IPT, which includes both local & global aggregation. I will remove the misleading comments in the next commit. Thank you for raising this issue!
