### ISSUE TITLE
Problems during training

### ISSUE THREAD

**Issue by xiaoxiaodadada** [YuchuanTian/U-DiT#6]
Thank you so much for your great work.
I have a problem updating ema while running the training code as required and I can't solve it, can you help me?

Traceback (most recent call last):
  File "/U-DiT-main/train.py", line 326, in <module>
    main(args, unparsed)
  File "/U-DiT-main/train.py", line 223, in main
    update_ema(ema, model.module if world_size > 1 else model, decay=0)  # Ensure EMA is initialized with synced weights
  File "/miniconda/envs/UDiT/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/U-DiT-main/train.py", line 48, in update_ema
    ema_params[name].mul_(decay).add_(param.data, alpha=1 - decay)
KeyError: 'module.x_embedder.proj.weight'

**Comment by YuchuanTian** [comment]
Thanks for raising this issue! Probably I need some further information:
1. How many processes have you inited at the same time?
2. Are you loading checkpoints, or just training from scratch?
Thank you!

**Comment by xiaoxiaodadada** [comment]
Here are my training instructions: 
CUDA_VISIBLE_DEVICES=6 torchrun --nnodes=1 --nproc_per_node=1 train.py --data-path=data/ --image-size=256
I only used one card and started training from scratch

**Comment by xiaoxiaodadada** [comment]
CUDA_VISIBLE_DEVICES=6,7 torchrun --nnodes=1 --nproc_per_node=2 train.py --data-path=data/ --image-size=256
Change it to this and it will run normally.

**Comment by YuchuanTian** [comment]
I guess I know the reason. If you are training with a single card, could you please replace "torchrun --nnodes=1 --nproc_per_node=1" with "python" and give it another try? Thank you.

**Comment by xiaoxiaodadada** [comment]
Thanks, that's ok

**Comment by DDgogogo** [comment]
> 感谢您提出这个问题！我可能需要一些更多信息：
> 
> 1. 您同时启动了多少个进程？
> 2. 你是在加载检查点，还是只是从头开始训练？
>    谢谢！

2
training from scratch
