### ISSUE TITLE
Have you tried skip connections for each block?

### ISSUE THREAD

**Issue by LinB203** [YuchuanTian/U-DiT#7]
Have you tried skip connections for each block?

**Comment by YuchuanTian** [comment]
No I haven't. I think block-wise skip connection is hardly affordable both in terms of GPU memory and FLOPs:
1. All intermediate feature maps have to be stored until backward;
2. Merging skip connections with backbone involves fully-connected channel reduction, which is terribly costly.

Above all, I think block-wise skip connection is probably not a good choice for DiT designs.

**Comment by LinB203** [comment]
Because what I found when I looked at their code in hunyuanDiT is that they are block-wise skip connection. However, the model seems to converge very slowly after I trained it using a similar architecture.
