### ISSUE TITLE
What is the environment of train?

### ISSUE THREAD

**Issue by water221** [YuchuanTian/U-DiT#9]
It's really a great job!
At present, I only have a single GPU 24G memory, can I train this project locally, if you modify some parameters can train, can you say where you can modify in addition to modifying batch_size?
Also, can you explain your train environment, such as how many GPU cards are used?
Thank you so much

**Comment by YuchuanTian** [comment]
I am glad you like our work! Thank you!

We used 8-card NVIDIA A100. I think it is even hard to train the U-DiT-S version with a single GPU... Anything I could do to help you?

**Comment by water221** [comment]
I'm going to tune down batch_size try it first, thank you very much for your answer

**Comment by YuchuanTian** [comment]
My pleasure! Another suggestion: it would be good to train U-DiTs with checkpoints to trade time for GPU memory

**Comment by water221** [comment]
Ok, I'll try
